
meta:
  engine: 4.1.0
  author: phiwan


units:
  kx: cx
  ky: cy
  # halfs
  khx: kx/2
  khy: ky/2
  # padding
  px: kx + 2
  py: ky + 2
  # adjust preview rendering
  $default_width: cx
  $default_height: cy


points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        outer:
          rows.bottom.skip: true
        pinky:
          key.stagger: 5
        ring:
          key.stagger: 10
        middle:
          key.stagger: 7
        index:
          key.stagger: -7
        inner:
          key.stagger: 0
      rows:
        bottom:
        home:
        top:
    thumbs:
      key:
        spread: 22
      anchor:
        ref: matrix_inner_bottom
        shift: [-24, -ky]
      columns:
        left:
          key.splay: 0
        middle:
          key.splay: -15
          key.shift: [0, -3]
        right:
          key.splay: -15
          key.shift: [0, -6]
      rows:
        cluster:
    # screw points


outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx, ky]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-khx-2,khy+2]
        - ref: matrix_outer_top
          shift: [khx-2,khy+2]
        - ref: matrix_pinky_top
          shift: [-khx-2,khy+2]
        - ref: matrix_pinky_top
          shift: [khx-2,khy+2]
        - ref: matrix_ring_top
          shift: [-khx-2,khy+2]
        - ref: matrix_ring_top
          shift: [khx-2,khy+2]
        - ref: matrix_middle_top
          shift: [-khx-2,khy+2]
        - ref: matrix_middle_top
          shift: [khx+2,khy+2]
        - ref: matrix_index_top
          shift: [-khx+2,khy+2]
        - ref: matrix_inner_top
          shift: [30.6,khy+2]
        - ref: thumbs_right_cluster
          shift: [khx+2,khy+1]  # not an error
        - ref: thumbs_right_cluster
          shift: [khx+2,-khy-2]
        - ref: thumbs_right_cluster
          shift: [-khx,-khy-2]
        - ref: thumbs_middle_cluster
          shift: [-khx-1,-khy-2]  # not an error
        - ref: thumbs_left_cluster
          shift: [-khx-2,-khy-2]
        - ref: matrix_pinky_bottom
          shift: [khx,-khy-2]
        - ref: matrix_pinky_bottom
          shift: [-khx-2,-khy-2]
        - ref: matrix_outer_home
          shift: [khx-2,-khy-2]
        - ref: matrix_outer_home
          shift: [-khx-2,-khy-2]
      fillet: 2
  combined:
    - name: board
    - operation: stack
      name: keys


pcbs:
  pcb:
    outlines.main.outline: board
    footprints:

      # hotswap choc
      switches:
        what: choc
        where: true
        params:
          keycaps: true
          #keycaps: false   # outline on the pcb
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      # smd diodes
      diodes:
        what: combo_diode
        where: true
        params:
          include_smd: true
          include_tht: false
          #include_via: false
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]

      # mcu with reversible pins
      xiao_ble:
        what: xiao_ble_smd_reversible
        params:
          D0: "rtop"
          D1: "rhome"
          D2: "rbottom"
          D3: "rthumbs"
          D4: "sda"
          D5: "scl"
          D6: "cinner"
          D7: "cindex"
          D8: "cmiddle"
          D9: "cring"
          D10: "cpinky"
        where:
          ref: matrix_inner_top
          shift: [kx+2, -2]

